version: '3.8'

services:
   backend:
      container_name: backend
      restart: always
      build: ./backend
      ports:
         - 3000:3000
      environment:
         VITE_API: ${VITE_API}

   client:
      container_name: client
      links:
         - "backend"
      restart: always
      build: ./client
      ports:
         - 4000:5173
      environment:
         CLIENT_SERVER: ${CLIENT_SERVER}